services:
  minio:
    image: minio/minio
    restart: always
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=docker
      - MINIO_ROOT_PASSWORD=secretdocker
    volumes:
      - ./minio/data:/data
    ports:
      - 9000:9000
      - 9001:9001
  database:
    image: postgres
    environment:
      POSTGRES_DB: kauefraga-dev-api
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    ports:
      - 5432:5432

volumes:
  minio:
  database:
